services:
    kachkaev_assets_version.assets_version_manager:
        class: "%kachkaev_assets_version.manager.class%"
        arguments:
            - "%kachkaev_assets_version.filename%"
            - "%kachkaev_assets_version.parametername%"